# Generated by Django 3.2.4 on 2021-06-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_rename_description_contact_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('salary', models.FloatField()),
            ],
        ),
    ]
