# Generated by Django 3.2.4 on 2021-06-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
